namespace CollectorsVault.Server.Contracts
{
    /// <summary>
    /// Request payload for creating a new user account.
    /// </summary>
    public class SignupRequest
    {
        /// <summary>The desired username.</summary>
        public string Username { get; set; } = string.Empty;
    }

    /// <summary>
    /// Response returned after a successful signup, containing the TOTP configuration
    /// needed to register the account in an authenticator app.
    /// </summary>
    public class SignupResponse
    {
        /// <summary>The registered username.</summary>
        public string Username { get; set; } = string.Empty;

        /// <summary>
        /// The <c>otpauth://totp/…</c> URI that encodes the TOTP secret and issuer.
        /// Render this as a QR code for the user to scan with their authenticator app.
        /// </summary>
        public string TotpUri { get; set; } = string.Empty;

        /// <summary>
        /// The Base32-encoded TOTP secret. Display this as a fallback for users who
        /// cannot scan the QR code and need to enter the key manually.
        /// </summary>
        public string TotpSecret { get; set; } = string.Empty;
    }

    /// <summary>
    /// Request payload for authenticating an existing user.
    /// </summary>
    public class LoginRequest
    {
        /// <summary>The user's registered username.</summary>
        public string Username { get; set; } = string.Empty;

        /// <summary>
        /// The current 6-digit TOTP code generated by the user's authenticator app.
        /// </summary>
        public string TotpCode { get; set; } = string.Empty;
    }

    /// <summary>
    /// Response returned after a successful login.
    /// </summary>
    public class LoginResponse
    {
        /// <summary>A signed JWT bearer token to include in subsequent API requests.</summary>
        public string Token { get; set; } = string.Empty;

        /// <summary>The authenticated user's username.</summary>
        public string Username { get; set; } = string.Empty;
    }
}
