using System.Collections.Generic;
using System.Text.Json;
using CollectorsVault.Server.Models;
using Microsoft.EntityFrameworkCore;

namespace CollectorsVault.Server.Data
{
    public class VaultDbContext : DbContext
    {
        public VaultDbContext(DbContextOptions<VaultDbContext> options) : base(options) { }

        public DbSet<User> Users { get; set; }
        public DbSet<Book> Books { get; set; }
        public DbSet<Movie> Movies { get; set; }
        public DbSet<Game> Games { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<User>()
                .ToTable("User")
                .HasIndex(u => u.Username)
                .IsUnique();

            modelBuilder.Entity<VaultItem>()
                .UseTpcMappingStrategy()
                .HasOne(v => v.User)
                .WithMany(u => u.VaultItems)
                .HasForeignKey(v => v.UserId)
                .OnDelete(DeleteBehavior.Cascade);

            modelBuilder.Entity<Book>().ToTable("Book");
            modelBuilder.Entity<Movie>().ToTable("Movie");
            modelBuilder.Entity<Game>().ToTable("Game");

            // With TPC on SQLite, be explicit that keys are generated by the database.
            // This prevents EF from attempting to insert the default CLR value (0) for Id.
            modelBuilder.Entity<Book>()
                .Property(b => b.Id)
                .ValueGeneratedOnAdd();

            modelBuilder.Entity<Movie>()
                .Property(m => m.Id)
                .ValueGeneratedOnAdd();

            modelBuilder.Entity<Game>()
                .Property(g => g.Id)
                .ValueGeneratedOnAdd();

            // Store Authors and Subjects as JSON arrays in a single TEXT column.
            modelBuilder.Entity<Book>()
                .Property(b => b.Authors)
                .HasColumnType("TEXT")
                .HasConversion(
                    v => JsonSerializer.Serialize(v, (JsonSerializerOptions)null!),
                    v => JsonSerializer.Deserialize<List<string>>(v, (JsonSerializerOptions)null!) ?? new List<string>());

            modelBuilder.Entity<Book>()
                .Property(b => b.Subjects)
                .HasColumnType("TEXT")
                .HasConversion(
                    v => v == null ? null : JsonSerializer.Serialize(v, (JsonSerializerOptions)null!),
                    v => v == null ? null : JsonSerializer.Deserialize<List<string>>(v, (JsonSerializerOptions)null!));

            // Store BookFormat enum as its name string for readability.
            // An empty/unrecognised string is treated as null (no format set).
            modelBuilder.Entity<Book>()
                .Property(b => b.BookFormat)
                .HasConversion(
                    v => v.HasValue ? v.Value.ToString() : null,
                    v => ParseBookFormatFromDb(v));
        }

        private static BookFormat? ParseBookFormatFromDb(string? v)
        {
            if (string.IsNullOrEmpty(v))
            {
                return null;
            }

            return System.Enum.TryParse<BookFormat>(v, ignoreCase: true, out var parsed)
                ? parsed
                : (BookFormat?)null;
        }
    }
}
